[build-system]
requires = ["setuptools>=65.5.1", "wheel>=0.38.4"]
build-backend = "setuptools.build_meta"

[project]
name = "redditClone"
version = "1.0"
description = "Reddit Clone Django Project"
requires-python = ">=3.12" 